language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*

before_install:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - composer self-update

install:
  - composer require symfony/symfony:${SYMFONY_VERSION}

script:
  - phpunit --coverage-clover=coverage.clover --coverage-text
  - phpcs --ignore=/vendor/* --extensions=php --encoding=utf-8 --standard=PSR2 -np .

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="b64151e5c9d22d8cae4165f73c8c90d4542f1bb03e8e424a6301c3cbbc24ce4b" --format=php-clover coverage.clover
